<?php


function hmp_auth0_preprocess_page(&$var) {
	$user_data = hmp_auth0_get_data();
	if($user_data['email'] != '' && !isset($_GET['formstack'])) {
		$hmp_auth0 = \Drupal::state()->get('hmp_auth0');
		$urls = explode(',',$hmp_auth0['auth0_form_urls']);
		$query_string = '';
		$uri = $_SERVER['REQUEST_URI'];
		foreach($urls as $url) {
			$form = explode('|',$url);
			if(strpos($uri,$form[0]) !== FALSE) {
				$query_string .= '&form_id=' . $form[1];
				$field_groups = explode(',',$hmp_auth0['auth0_fields']);
				foreach($field_groups as $field_group) {
					$field = explode('|',$field_group);
					if($user_data[$field[0]]) {
							$query_string .= '&' . $field[1] . '=' . $user_data[$field[0]];
					}
				}
			}
		}
		if($query_string != '') {

			$query_string = '?formstack=1' . $query_string;
			$var['page']['content'] = t("<script type='text/javascript' src='https://hmp.formstack.com/forms/js.php/wcln$query_string'></script>");		}
	}
}

function hmp_auth0_get_data() {
	$uid = \Drupal::currentUser()->id();
	if($uid != 0) {
	$user = \Drupal\user\Entity\User::load($uid);
	$email = $user->getEmail();
	$token = hmp_auth0_get_token();

	$curl = curl_init();

	curl_setopt_array($curl, array(
		CURLOPT_URL => "https://hmpsso.auth0.com/api/v2/users-by-email?email=$email",
		CURLOPT_RETURNTRANSFER => true,
		CURLOPT_ENCODING => "",
		CURLOPT_MAXREDIRS => 10,
		CURLOPT_TIMEOUT => 30,
		CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
		CURLOPT_CUSTOMREQUEST => "GET",
		CURLOPT_HTTPHEADER => array(
		"authorization: Bearer $token"
		),
	));

	$response = curl_exec($curl);
	$err = curl_error($curl);

	curl_close($curl);

	if ($err) {
		echo "cURL Error #:" . $err;
	} else {
		$data = json_decode($response);
		$user_data = array(
			'email' => $user->getEmail(),
			'first_name' => $data[0]->user_metadata->first_name,
			'last_name' => $data[0]->user_metadata->last_name,
			'degree' => $data[0]->user_metadata->degree,
			'specialty' => $data[0]->user_metadata->specialty,
			'worksetting' => $data[0]->user_metadata->worksetting,
			'company' => $data[0]->user_metadata->company,
			'state' => $data[0]->user_metadata->state,
		);
		return $user_data;
	}
	return null;
	}
}

function hmp_auth0_get_token() {
	$curl = curl_init();

	curl_setopt_array($curl, array(
		CURLOPT_URL => "https://hmpsso.auth0.com/oauth/token",
		CURLOPT_RETURNTRANSFER => true,
		CURLOPT_ENCODING => "",
		CURLOPT_MAXREDIRS => 10,
		CURLOPT_TIMEOUT => 30,
		CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
		CURLOPT_CUSTOMREQUEST => "POST",
		CURLOPT_POSTFIELDS => "{\"grant_type\":\"client_credentials\",\"client_id\": \"HDfEcyN3sCacfiEYsOEEmgbvidSMTf14\",\"client_secret\": \"hjnU5sIS-Z--x8YvjTinbP3DfLFe848vbDdjyLl-iTF54jwV1TQ44K3eWZdAnMd5\",\"audience\": \"https://hmpsso.auth0.com/api/v2/\"}",
		CURLOPT_HTTPHEADER => array(
		"content-type: application/json"
		),
	));

	$response = curl_exec($curl);
	$err = curl_error($curl);

	curl_close($curl);

	if ($err) {
		echo "cURL Error #:" . $err;
	} else {
		$data = json_decode($response);
		return $data->access_token;
	}
}

?>